#!/usr/bin/env python

# Copyright 2015 Bracket Computing, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
#
# https://github.com/brkt/brkt-sdk-java/blob/master/LICENSE
#
# or in the "license" file accompanying this file. This file is
# distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and
# limitations under the License.

import subprocess
import sys

# Get the dependencies classpath from the Maven build.
print 'Determining classpath.'

found_classpath = False
for line in subprocess.check_output(['mvn', 'dependency:build-classpath']).split('\n'):
    if found_classpath:
        classpath = line
        break
    if 'Dependencies classpath:' in line:
        found_classpath = True

print 'Running integration test.'
classpath = 'target/test-classes:target/classes:' + classpath
java_command = ['java', '-classpath', classpath, 'com.brkt.client.IntegrationTest']
if len(sys.argv) > 1:
    java_command.extend(sys.argv[1:])
# print ' '.join(java_command)
try:
    subprocess.check_call(java_command)
except subprocess.CalledProcessError as e:
    exit(e.returncode)
